version: '3.8'

services:
    ui:
        container_name: ui
        build: ./ui
        depends_on:
          - api
        ports:
          - ${WEB_PORT}:${WEB_PORT}

    api:
        container_name: api
        build: ./api
        depends_on:
            - postgres
        env_file:
            - docker.env
        ports:
            - ${PORT}:${PORT}
        links:
          - postgres

    postgres:
        container_name: postgres
        image: postgres:latest
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - /data/postgres:/data/postgres
        env_file:
            - docker.env
        networks:
            - postgres

    pgadmin:
        container_name: pgadmin
        links:
            - postgres:postgres
        image: dpage/pgadmin4
        ports:
            - "8080:80"
        volumes:
            - /data/pgadmin:/root/.pgadmin
        env_file:
            - docker.env
        networks:
            - postgres

networks:
    postgres:
        driver: bridge