steps:
    - name: gcr.io/cloud-builders/docker
      args:
          - build
          - '--no-cache'
          - '-t'
          - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
          - ui
          - '-f'
          - ui/Dockerfile
      id: Build
    - name: gcr.io/cloud-builders/docker
      args:
          - push
          - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      id: Push
    - name: gcr.io/google.com/cloudsdktool/cloud-sdk
      args:
          - run
          - services
          - update
          - $_SERVICE_NAME
          - '--platform=managed'
          - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
          - >-
              --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
          - '--region=$_DEPLOY_REGION'
          - '--quiet'
      id: Deploy
      entrypoint: gcloud
images:
    - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
timeout: 900s
options:
    substitutionOption: ALLOW_LOOSE
substitutions:
    _DEPLOY_REGION: us-central1
    _GCR_HOSTNAME: us.gcr.io
    _PLATFORM: managed
    _SERVICE_NAME: mattmaxwell-prod-ui
    _LABELS: gcb-trigger-id=3ff24e57-10a6-4bbe-b987-b66e8c703a6e
    _TRIGGER_ID: 3ff24e57-10a6-4bbe-b987-b66e8c703a6e
tags:
    - gcp-cloud-build-deploy-cloud-run
    - gcp-cloud-build-deploy-cloud-run-managed
    - mattmaxwell-prod-ui